made the grades gradients as to distinguish between grades within catagories
Aspine/aspine pull request #150
Opened 2020-10-25 21:41 UTC by andOrlando

This was issue #50 

There were two ways I did this:
First one is a graident between two distinct colors which you can pick by editing the constants
Second one is a gradient from one color to black, but the color varies based on what grade range you're in using colors similar to the old verison.

Pick whichever you think fits best, I'm personally in favor of the latter and its closer to what we currently have.

2020-11-20 23:03 UTC, notrodes commented
is this needed?

2020-11-20 23:22 UTC, notrodes approved these changes
Ok

2020-11-20 23:22 UTC, notrodes commented on public/js/extraFunctions.js
> +  for (i=0; i<3; i++) {
```suggestion
  for (const channel of color_rgb) {
```

2020-11-20 23:22 UTC, notrodes commented on public/js/extraFunctions.js
> +    const color = Math.round(color_rgb[i]-percentage*color_rgb[i]).toString(16)
```suggestion
    const color = Math.round(channel-percentage*channel).toString(16);
```

2020-11-20 23:22 UTC, notrodes commented on public/js/extraFunctions.js
> +
### semi-colons

2020-11-20 23:31 UTC, notrodes requested changes

2020-11-20 23:31 UTC, notrodes commented on public/js/extraFunctions.js
>  }
ooops I made mistake, fix these first

2020-11-25 00:02 UTC, notrodes approved these changes

2020-11-25 02:48 UTC, psvenk commented
I'll take a look at this tomorrow and merge if there are no objections or questions.

2020-11-25 22:24 UTC, psvenk requested changes
- Grades close to 100% are given a very bright green color which is not very pretty.
- When creating an assignment, the initial color is the default green and not the color that corresponds to a grade of 100% (the default upon creating an assignment).

2020-12-10 21:47 UTC, psvenk commented
One idea that was brought up yesterday was that we abandon this pull request (sorry @andOrlando) and instead use the CSS color variables for the colors that are used for grades, because this would make it easier to adapt grade coloring to dark mode (see #195).

2020-12-13 02:45 UTC, andOrlando commented
NOOOOoOoOOOOOoOooooooooooo

2020-12-20 03:28 UTC, closed without merging