Dark Mode
Aspine/aspine pull request #195
Opened 2020-12-09 01:21 UTC by jadebuckwalter

Create a switch that when toggled, switches Aspine to Dark Mode.

2020-12-09 01:38 UTC, jadebuckwalter commented
Some notes about Dark Mode:

Aspine switches to Dark Mode by changing the values of color variables in the CSS files, either by detecting the color scheme that the device is already using or by toggling a switch in the upper right-hand corner. If the device is already in Dark Mode, Aspine will automatically change to Dark Mode upon loading. However, the toggle works whether or not the device is already in Dark Mode.

While working on this, I found many instances of text that did not have a color variable assigned to it in the CSS file. This is a problem because the text will not change color when Dark Mode is toggled, making it hard to read. I am fairly confident that I fixed all of these instances, but if there are any remaining (except for the schedule - more on that below), please let me know.

The Dark Mode toggle does not quite work with the Schedule tab (yet). The colors for each class period are stored in an array in the JS file rather than in the CSS file, so they are only read when the page initially loads. This is not a huge problem, because the text can still be read when hovered over, but it is far from ideal and something I am still working on.

I also changed the bar graph icon I had previously added to a similar icon from Material Icons. This makes it easier to change the color of the icon.

2020-12-09 18:33 UTC, tektaxi commented
Dark Mode Bugs:
1. Aspine Header and small clock can't be clicked on to take you to their respective pages. (grades, clock). The pointer also doesn't change on hover, so CSS Isn't detecting it.
2. Schedule Tab doesn't switch when the mode switches
3. Hide dark mode toggle on small screens.
4. Store user preference of color scheme in localstorage

Add any more issues here

2020-12-11 23:51 UTC, jadebuckwalter commented
Didn't have enough space to write this in the commit message, but along with changing the border color of the input box in dark mode to make it visible, I changed the color of the label text to a lighter shade of gray in dark mode to increase the contrast.

2020-12-13 23:13 UTC, notrodes requested changes

2020-12-13 23:13 UTC, notrodes commented on public/js/home.js
> +function getMode() {
Delete, don't need it, see later comments for why.

2020-12-13 23:13 UTC, notrodes commented on public/js/home.js
> +    let darkModeColors = ["#00290e", "#003d14", "#00551d", "#007a29", "#008f30", "#00a336", "#00b83d", "#00cc44"];
delete, use css variables in the colors list

2020-12-13 23:13 UTC, notrodes commented on public/js/home.js
> +            if (getMode()) {
delete if, both branches now use colors[] because they use variables

2020-12-13 23:13 UTC, notrodes commented on public/js/home.js
> +            if (getMode()) {
same as above

2020-12-13 23:56 UTC, psvenk requested changes

2020-12-13 23:56 UTC, psvenk commented on public/js/home.js
> + }
This should be substantially reworked. The status quo is that the color definitions are repeated between `home.css` and `home.js`. Instead, `:root` and `@media (prefers-color-scheme: dark) { :root { ... } }` can be changed to be `body` and `body.dark`, and we can set/unset the `dark` class in JS according to `window.matchMedia('(prefers-color-scheme: dark)').matches` and the setting in `localStorage` (if any). Then, this function would simply need to toggle the `dark` class on the `body` element.

2020-12-13 23:56 UTC, psvenk commented on public/home.html
> +  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
This should be included via `node_modules` and exposed to the frontend via `serve.js`. I can take care of this; I am just noting this here as a to-do item.

2020-12-14 17:09 UTC, psvenk approved these changes
Looks good to me.

2020-12-14 18:01 UTC, tektaxi approved these changes
Now that we've cleaned it up it looks great to me! Ready to merge I think.

2020-12-15 00:00 UTC, psvenk requested changes
Some more code style changes:

2020-12-15 00:00 UTC, psvenk commented on public/js/home.js
> + }
Simplify code by removing unused variables and needlessly verbose comments
```suggestion
// Toggle between dark and light mode
function darkMode() {
    document.body.classList.toggle("dark");
    localStorage.setItem("color-scheme",
        document.querySelector("body").classList.contains("dark") ?
            'dark' : 'light');
}
```

2020-12-15 00:00 UTC, psvenk commented on public/js/home.js
> +    }
This can be greatly simplified (and usage of `var` should be avoided):
```suggestion
    const preferredMode = localStorage.getItem("color-scheme") || currentMode;
```

2020-12-15 00:00 UTC, psvenk commented on public/js/home.js
> +    else {
`else` should be on the same line as the closing brace
```suggestion
    } else {
```

2020-12-15 00:30 UTC, notrodes requested changes

2020-12-15 00:30 UTC, notrodes commented on public/js/home.js
> +};
```suggestion
// detect color scheme and set slider
window.addEventListener("load", function loadMode() {
    // loads current os mode and sets slider accordingly
    const slider = document.getElementById("dark-check");
    const preferredMode = localStorage.getItem('color-scheme');
    if (preferredMode ? preferredMode === 'dark' :
        window.matchMedia("(prefers-color-scheme: dark)").matches) {
        document.body.classList.toggle("dark");
        // sets the slider to match the actual mode
        slider.checked = true;
    }
});
```
Modern code

2020-12-15 00:35 UTC, psvenk commented on public/js/home.js
> +};
With clearer / more idiomatic indentation:
```suggestion
// detect color scheme and set slider
window.addEventListener("load", function loadMode() {
    // loads current os mode and sets slider accordingly
    const slider = document.getElementById("dark-check");
    const preferredMode = localStorage.getItem('color-scheme');
    if (preferredMode ? preferredMode === 'dark' :
            window.matchMedia("(prefers-color-scheme: dark)").matches) {
        document.body.classList.toggle("dark");
        // sets the slider to match the actual mode
        slider.checked = true;
    }
});
```

2020-12-15 00:45 UTC, psvenk approved these changes

2020-12-15 00:46 UTC, notrodes approved these changes

2020-12-15 00:47 UTC, merged